package org.e.payment.webservice.client.vo.V2.bankTran;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-02T10:09:54.560-04:30
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://201.249.156.12/webservice", name = "BankTranServiceV2")
@XmlSeeAlso({ObjectFactory.class})
public interface BankTranServiceV2 {

    @WebMethod(operationName = "Recharge")
    @RequestWrapper(localName = "Recharge", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.V2.bankTran.Recharge")
    @ResponseWrapper(localName = "RechargeResponse", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.V2.bankTran.RechargeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.e.payment.webservice.client.vo.V2.bankTran.RechargeResponseV2 recharge(
        @WebParam(name = "RechargeRequest", targetNamespace = "")
        org.e.payment.webservice.client.vo.V2.bankTran.RechargeRequestV2 rechargeRequest
    );
}
