
package org.e.payment.webservice.client.vo.V2.bankTran;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-02T10:09:54.522-04:30
 * Generated source version: 3.1.12
 * 
 */
public final class BankTranServiceV2_BankTranServiceV2ImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://201.249.156.12/webservice", "BankTranServiceV2ImplService");

    private BankTranServiceV2_BankTranServiceV2ImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankTranServiceV2ImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankTranServiceV2ImplService ss = new BankTranServiceV2ImplService(wsdlURL, SERVICE_NAME);
        BankTranServiceV2 port = ss.getBankTranServiceV2ImplPort();  
        
        {
        System.out.println("Invoking recharge...");
        org.e.payment.webservice.client.vo.V2.bankTran.RechargeRequestV2 _recharge_rechargeRequest = null;
        org.e.payment.webservice.client.vo.V2.bankTran.RechargeResponseV2 _recharge__return = port.recharge(_recharge_rechargeRequest);
        System.out.println("recharge.result=" + _recharge__return);


        }

        System.exit(0);
    }

}
