package org.e.payment.webservice.client.vo.V2.bankTran;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-11-02T10:09:54.565-04:30
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "BankTranServiceV2ImplService", 
                  wsdlLocation = "http://localhost:9095/webservice/v2/bankTran?wsdl",
                  targetNamespace = "http://201.249.156.12/webservice") 
public class BankTranServiceV2ImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://201.249.156.12/webservice", "BankTranServiceV2ImplService");
    public final static QName BankTranServiceV2ImplPort = new QName("http://201.249.156.12/webservice", "BankTranServiceV2ImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9095/webservice/v2/bankTran?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankTranServiceV2ImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9095/webservice/v2/bankTran?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankTranServiceV2ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankTranServiceV2ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankTranServiceV2ImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BankTranServiceV2ImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankTranServiceV2ImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankTranServiceV2ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BankTranServiceV2
     */
    @WebEndpoint(name = "BankTranServiceV2ImplPort")
    public BankTranServiceV2 getBankTranServiceV2ImplPort() {
        return super.getPort(BankTranServiceV2ImplPort, BankTranServiceV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankTranServiceV2
     */
    @WebEndpoint(name = "BankTranServiceV2ImplPort")
    public BankTranServiceV2 getBankTranServiceV2ImplPort(WebServiceFeature... features) {
        return super.getPort(BankTranServiceV2ImplPort, BankTranServiceV2.class, features);
    }

}
