package org.e.payment.webservice.client.vo.bankTran;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-20T19:12:50.773-04:30
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "BankTranServiceImplService", 
                  wsdlLocation = "http://localhost:9095/webservice/bankTran?wsdl",
                  targetNamespace = "http://201.249.156.12/webservice") 
public class BankTranServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://201.249.156.12/webservice", "BankTranServiceImplService");
    public final static QName BankTranServiceImplPort = new QName("http://201.249.156.12/webservice", "BankTranServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9095/webservice/bankTran?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankTranServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9095/webservice/bankTran?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankTranServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankTranServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankTranServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BankTranServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankTranServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankTranServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BankTranService
     */
    @WebEndpoint(name = "BankTranServiceImplPort")
    public BankTranService getBankTranServiceImplPort() {
        return super.getPort(BankTranServiceImplPort, BankTranService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankTranService
     */
    @WebEndpoint(name = "BankTranServiceImplPort")
    public BankTranService getBankTranServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BankTranServiceImplPort, BankTranService.class, features);
    }

}
