
package org.e.payment.webservice.client.vo.bankTran;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-20T19:12:50.729-04:30
 * Generated source version: 3.1.12
 * 
 */
public final class BankTranService_BankTranServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://201.249.156.12/webservice", "BankTranServiceImplService");

    private BankTranService_BankTranServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankTranServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankTranServiceImplService ss = new BankTranServiceImplService(wsdlURL, SERVICE_NAME);
        BankTranService port = ss.getBankTranServiceImplPort();  
        
        {
        System.out.println("Invoking recharge...");
        org.e.payment.webservice.client.vo.bankTran.RechargeRequest _recharge_rechargeRequest = null;
        org.e.payment.webservice.client.vo.bankTran.RechargeResponse2 _recharge__return = port.recharge(_recharge_rechargeRequest);
        System.out.println("recharge.result=" + _recharge__return);


        }
        {
        System.out.println("Invoking reverse...");
        org.e.payment.webservice.client.vo.bankTran.ReverseRequest _reverse_reverseRequest = null;
        org.e.payment.webservice.client.vo.bankTran.ReverseResponse2 _reverse__return = port.reverse(_reverse_reverseRequest);
        System.out.println("reverse.result=" + _reverse__return);


        }

        System.exit(0);
    }

}
