package org.e.payment.webservice.client.vo.bankTran;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-20T19:12:50.766-04:30
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://201.249.156.12/webservice", name = "BankTranService")
@XmlSeeAlso({ObjectFactory.class})
public interface BankTranService {

    @WebMethod(operationName = "Recharge")
    @RequestWrapper(localName = "Recharge", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.bankTran.Recharge")
    @ResponseWrapper(localName = "RechargeResponse", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.bankTran.RechargeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.e.payment.webservice.client.vo.bankTran.RechargeResponse2 recharge(
        @WebParam(name = "RechargeRequest", targetNamespace = "")
        org.e.payment.webservice.client.vo.bankTran.RechargeRequest rechargeRequest
    );

    @WebMethod(operationName = "Reverse")
    @RequestWrapper(localName = "Reverse", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.bankTran.Reverse")
    @ResponseWrapper(localName = "ReverseResponse", targetNamespace = "http://201.249.156.12/webservice", className = "org.e.payment.webservice.client.vo.bankTran.ReverseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.e.payment.webservice.client.vo.bankTran.ReverseResponse2 reverse(
        @WebParam(name = "ReverseRequest", targetNamespace = "")
        org.e.payment.webservice.client.vo.bankTran.ReverseRequest reverseRequest
    );
}
