package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.BankInterfaceStatistics;
import com.zbensoft.e.payment.db.domain.BankInterfaceStatisticsKey;

public interface BankInterfaceStatisticsService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    int deleteByPrimaryKey(BankInterfaceStatisticsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    int insert(BankInterfaceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    int insertSelective(BankInterfaceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    BankInterfaceStatistics selectByPrimaryKey(BankInterfaceStatisticsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    int updateByPrimaryKeySelective(BankInterfaceStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_interface_statistics
     *
     * @mbg.generated Wed Aug 02 08:36:19 VET 2017
     */
    int updateByPrimaryKey(BankInterfaceStatistics record);
    
    List<BankInterfaceStatistics> selectPageMonth(BankInterfaceStatistics record,String type);

	int countMonth(BankInterfaceStatistics bankInterfaceStatistics,String type);

	List<BankInterfaceStatistics> selectPage(BankInterfaceStatistics bankInterfaceStatistics);

	int count(BankInterfaceStatistics bankInterfaceStatistics);

	List<BankInterfaceStatistics> selectPageDay(BankInterfaceStatistics bankInterfaceStatistics, String type);

	int countDay(BankInterfaceStatistics bankInterfaceStatistics, String type);

	List<BankInterfaceStatistics> selectPageDailyDay(BankInterfaceStatistics bankInterfaceStatistics, String type);

	int countDailyDay(BankInterfaceStatistics bankInterfaceStatistics, String type);

}