package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.BankCardType;
import com.zbensoft.e.payment.db.domain.BankInfo;

public interface BankCardTypeService {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    int deleteByPrimaryKey(Integer bankCardTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    int insert(BankCardType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    int insertSelective(BankCardType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    BankCardType selectByPrimaryKey(Integer bankCardTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    int updateByPrimaryKeySelective(BankCardType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card_type
     *
     * @mbg.generated Tue Oct 24 10:09:06 CST 2017
     */
    int updateByPrimaryKey(BankCardType record);
    int deleteAll();
    BankCardType selectByName(String name);
   	int count(BankCardType record);
   	List<BankCardType> selectPage(BankCardType record);
	boolean isExist(BankCardType bankCardType);
}
