package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.BankInfo;
import com.zbensoft.e.payment.db.domain.SysUser;

public interface BankInfoService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int deleteByPrimaryKey(String bankId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int insert(BankInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int insertSelective(BankInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	BankInfo selectByPrimaryKey(String bankId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(BankInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int updateByPrimaryKey(BankInfo record);

	List<BankInfo> selectPage(BankInfo record);

	boolean isBankInfoExist(BankInfo bankInfo);

	void deleteAll();
	
	int count(BankInfo bankInfo);

	BankInfo selectByBankId(String bankId);
}