package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.BankTradeInfo;

public interface BankTradeInfoService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    int deleteByPrimaryKey(String refNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    int insert(BankTradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    int insertSelective(BankTradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     * @param orderNo 
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    BankTradeInfo selectByPrimaryKey(String bankId, String refNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    int updateByPrimaryKeySelective(BankTradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_trade_info
     *
     * @mbg.generated Sat Jul 29 19:00:28 VET 2017
     */
    int updateByPrimaryKey(BankTradeInfo record);

    int insertBatch(List<BankTradeInfo> recordList) throws Exception;

	void deleteAll(String bankId);
}