package com.zbensoft.e.payment.api.service.api;

import java.util.List;


import com.zbensoft.e.payment.db.domain.Bookkeepking;

public interface BookkeepkingService {
    
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String bookkeepkingSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int insert(Bookkeepking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int insertSelective(Bookkeepking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    Bookkeepking selectByPrimaryKey(String bookkeepkingSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Bookkeepking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookkeepking
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int updateByPrimaryKey(Bookkeepking record);
    
    List<Bookkeepking> selectPage(Bookkeepking record);
    boolean isExist(Bookkeepking bookkeepking);
    void deleteAll();
    int count(Bookkeepking bookkeepking);
}