package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ChargeReconciliationBank;
import com.zbensoft.e.payment.db.domain.ChargeReconciliationBankKey;
import com.zbensoft.e.payment.db.domain.ErrorHandlingBank;

public interface ChargeReconciliationBankService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int deleteByPrimaryKey(ChargeReconciliationBankKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int insert(ChargeReconciliationBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int insertSelective(ChargeReconciliationBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	ChargeReconciliationBank selectByPrimaryKey(ChargeReconciliationBankKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int updateByPrimaryKeySelective(ChargeReconciliationBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_reconciliation_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int updateByPrimaryKey(ChargeReconciliationBank record);
	List<ChargeReconciliationBank> selectPage(ChargeReconciliationBank record);



	int count(ChargeReconciliationBank chargeReconciliationBank);
}