package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ChargeErrorHandlingBank;
import com.zbensoft.e.payment.db.domain.ChargeErrorHandlingBankKey;
import com.zbensoft.e.payment.db.domain.ChargeReconciliationBank;

public interface ChargeErrorHandlingBankService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int deleteByPrimaryKey(ChargeErrorHandlingBankKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int insert(ChargeErrorHandlingBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int insertSelective(ChargeErrorHandlingBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	ChargeErrorHandlingBank selectByPrimaryKey(ChargeErrorHandlingBankKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int updateByPrimaryKeySelective(ChargeErrorHandlingBank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table charge_error_handling_bank
	 * @mbg.generated  Sat Sep 09 21:25:22 VET 2017
	 */
	int updateByPrimaryKey(ChargeErrorHandlingBank record);

	void deleteByBankIdAndTime(ChargeErrorHandlingBank chargeErrorHandlingBank);
	List<ChargeErrorHandlingBank> selectPage(ChargeErrorHandlingBank record);



	int count(ChargeErrorHandlingBank chargeErrorHandlingBank);
}