package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerUserActiveStatistics;

public interface ConsumerUserActiveStatisticsService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    int deleteByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    int insert(ConsumerUserActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    int insertSelective(ConsumerUserActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    ConsumerUserActiveStatistics selectByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    int updateByPrimaryKeySelective(ConsumerUserActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_statistics
     *
     * @mbg.generated Fri Dec 01 09:14:52 CST 2017
     */
    int updateByPrimaryKey(ConsumerUserActiveStatistics record);
    
    List<ConsumerUserActiveStatistics> selectPage(ConsumerUserActiveStatistics record);
    boolean isConsumerUserActiveStatisticsExist(ConsumerUserActiveStatistics record);
	int count(ConsumerUserActiveStatistics record);
}