package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerUserLoginHis;

public interface ConsumerUserLoginHisService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int deleteByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insert(ConsumerUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insertSelective(ConsumerUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    ConsumerUserLoginHis selectByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKeySelective(ConsumerUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKey(ConsumerUserLoginHis record);

	List<ConsumerUserLoginHis> selectPage(ConsumerUserLoginHis consumerUserLoginHis);

	int count(ConsumerUserLoginHis consumerUserLoginHis);

	void deleteAll();

	int countDistin(ConsumerUserLoginHis consumerUserLoginHisSer);
}