package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerRole;

public interface ConsumerRoleService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insert(ConsumerRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insertSelective(ConsumerRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	ConsumerRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int updateByPrimaryKeySelective(ConsumerRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consume_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int updateByPrimaryKey(ConsumerRole record);

	boolean isRoleExist(ConsumerRole role);
	ConsumerRole selectByConsumerRoleName(String name);
	int deleteAll();

	List<ConsumerRole> selectPage(ConsumerRole record);

	int count(ConsumerRole role);
}