package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerCoupon;

public interface ConsumerCouponService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int deleteByPrimaryKey(ConsumerCoupon key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insert(ConsumerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insertSelective(ConsumerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    ConsumerCoupon selectByPrimaryKey(ConsumerCoupon key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(ConsumerCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKey(ConsumerCoupon record);

	List<ConsumerCoupon> selectPage(ConsumerCoupon record);

	void deleteAll();

	int count(ConsumerCoupon consumerCoupon);

	//根据clapId进行查询
	List<ConsumerCoupon> selectByClapId(String consumerUserClapId);

	void updateByStatus(ConsumerCoupon consumerCoupon);
}