package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerFamilyGroupFamilyKey;


public interface ConsumerFamilyGroupFamilyService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group_family
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int deleteByPrimaryKey(ConsumerFamilyGroupFamilyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group_family
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int insert(ConsumerFamilyGroupFamilyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group_family
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int insertSelective(ConsumerFamilyGroupFamilyKey record);

	void deleteByGroupId(String consumerFamilyGroupId);

	int count(ConsumerFamilyGroupFamilyKey consumerFamilyGroupFamilyKey);

	List<ConsumerFamilyGroupFamilyKey> selectPage(ConsumerFamilyGroupFamilyKey consumerFamilyGroupFamilyKey);

	void deleteConsumerFamilyGroupFamily(ConsumerFamilyGroupFamilyKey consumerFamilyGroupFamilyKey);
	
	//根据组编号查询
	List<ConsumerFamilyGroupFamilyKey> selectByGroupId(String groupId);

}