package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerFamilyGroup;

public interface ConsumerFamilyGroupService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String consumerFamilyGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int insert(ConsumerFamilyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int insertSelective(ConsumerFamilyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    ConsumerFamilyGroup selectByPrimaryKey(String consumerFamilyGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(ConsumerFamilyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_family_group
     *
     * @mbg.generated Wed Jun 21 16:07:12 GMT+08:00 2017
     */
    int updateByPrimaryKey(ConsumerFamilyGroup record);

	int count(ConsumerFamilyGroup consumerFamilyGroup);

	List<ConsumerFamilyGroup> selectPage(ConsumerFamilyGroup consumerFamilyGroup);

	boolean isNameExist(ConsumerFamilyGroup consumerFamilyGroup);

	void deleteAll();

	int saveOrUpdate(List<String> list, String consumerFamilyGroupId,boolean deleteFlagAll);
	
	void statusEnable(String consumerFamilyGroupId);

	void statusDisable(String consumerFamilyGroupId);
}