package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import org.apache.http.client.config.RequestConfig;
import org.apache.http.impl.client.CloseableHttpClient;

import com.zbensoft.e.payment.api.common.ResponseRestEntity;
import com.zbensoft.e.payment.db.domain.ConsumerUserClap;

public interface ConsumerUserClapService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int deleteByPrimaryKey(String consumerUserClapId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insert(ConsumerUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insertSelective(ConsumerUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	ConsumerUserClap selectByPrimaryKey(String consumerUserClapId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ConsumerUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKey(ConsumerUserClap record);

	List<ConsumerUserClap> selectPage(ConsumerUserClap record);

	void deleteAll();

	int count(ConsumerUserClap consumerUserClap);
	
	//根据用户编号查询
	List<ConsumerUserClap> selectByUserId(String userId);
	ConsumerUserClap selectByUser(String userId);

	ConsumerUserClap selectByClapId(String username);

	ConsumerUserClap selectByIdNumber(String recvIdNumber);
	ConsumerUserClap selectByFamilyId(String FamilyId);

	List<ConsumerUserClap> selectByClapStoreNo(String clapStoreNo);

	ResponseRestEntity<ConsumerUserClap> synchronizeConsumerClap(ConsumerUserClap consumerUserClap, String userId, CloseableHttpClient httpClient, RequestConfig config, String URL_CLAP_GET_CLAP)  throws Exception;
}