package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerRoleUserKey;
import com.zbensoft.e.payment.db.domain.SysUsersAppKey;

public interface ConsumerRoleUserService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(ConsumerRoleUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(ConsumerRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(ConsumerRoleUserKey record);

	List<ConsumerRoleUserKey> selectPage(ConsumerRoleUserKey record);

	void deleteAll();

	ConsumerRoleUserKey selectByPrimaryKey(ConsumerRoleUserKey key);

	int updateByPrimaryKey(ConsumerRoleUserKey record);

	int updateByPrimaryKeySelective(ConsumerRoleUserKey record);

	int count(ConsumerRoleUserKey consumeRoleUser);

	List<ConsumerRoleUserKey> selectByUserId(String userId);

	

}