package com.zbensoft.e.payment.api.service.api;

import java.util.List;
import com.zbensoft.e.payment.db.domain.ConsumerUserActiveReport;
import com.zbensoft.e.payment.db.domain.MerchantActiveReport;

public interface ConsumerUserActiveReportService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    int deleteByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    int insert(ConsumerUserActiveReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    int insertSelective(ConsumerUserActiveReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    ConsumerUserActiveReport selectByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    int updateByPrimaryKeySelective(ConsumerUserActiveReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_user_active_report
     *
     * @mbg.generated Thu Nov 30 14:08:35 VET 2017
     */
    int updateByPrimaryKey(ConsumerUserActiveReport record);
	
	List<ConsumerUserActiveReport> selectPage(ConsumerUserActiveReport record);

	int deleteAll();

	int count(ConsumerUserActiveReport consumerUserActiveReport);
}
