package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerFamilyCoupon;

public interface ConsumerFamilyCouponService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int deleteByPrimaryKey(ConsumerFamilyCoupon key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insert(ConsumerFamilyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insertSelective(ConsumerFamilyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    ConsumerFamilyCoupon selectByPrimaryKey(ConsumerFamilyCoupon key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(ConsumerFamilyCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKey(ConsumerFamilyCoupon record);

	List<ConsumerFamilyCoupon> selectPage(ConsumerFamilyCoupon record);

	void deleteAll();

	int count(ConsumerFamilyCoupon consumerFamilyCoupon);

	List<ConsumerFamilyCoupon> selectByFamilyId(String familyId);

	void updateByStatus(ConsumerFamilyCoupon consumerFamilyCoupon);

	void deleteByCouponId(ConsumerFamilyCoupon consumerFamilyCoupon);
}