package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerGroupUserKey;
import com.zbensoft.e.payment.db.domain.ConsumerRoleUserKey;


public interface ConsumerGroupUserService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_group_user
     *
     * @mbg.generated Mon Jun 19 14:13:26 GMT+08:00 2017
     */
    int deleteByPrimaryKey(ConsumerGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_group_user
     *
     * @mbg.generated Mon Jun 19 14:13:26 GMT+08:00 2017
     */
    int insert(ConsumerGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_group_user
     *
     * @mbg.generated Mon Jun 19 14:13:26 GMT+08:00 2017
     */
    int insertSelective(ConsumerGroupUserKey record);

	void deleteByGroupId(String consumerGroupId);

	int count(ConsumerGroupUserKey consumerGroupUserKey);

	List<ConsumerGroupUserKey> selectPage(ConsumerGroupUserKey consumerGroupUserKey);

	void deleteConsumerGroupUser(ConsumerGroupUserKey consumerGroupUserKey);
	
	//
	List<ConsumerGroupUserKey> selectByGroupId(String groupId);
	List<ConsumerGroupUserKey> selectByUserId(String userId);

}