package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.App;
import com.zbensoft.e.payment.db.domain.ConsumptionType;

public interface ConsumptionTypeService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String billConsumptionTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(ConsumptionType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(ConsumptionType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	ConsumptionType selectByPrimaryKey(String billConsumptionTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(ConsumptionType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(ConsumptionType record);

	List<ConsumptionType> selectPage(ConsumptionType record);

	boolean isConsumptionTypeExist(ConsumptionType consumptionType);

	void deleteAll();

	int count(ConsumptionType consumptionType);
}