package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.CouponBuy;

public interface CouponBuyService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    int insert(CouponBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    int insertSelective(CouponBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    CouponBuy selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    int updateByPrimaryKeySelective(CouponBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_buy
     *
     * @mbg.generated Wed Jun 07 16:58:49 CST 2017
     */
    int updateByPrimaryKey(CouponBuy record);
    
    List<CouponBuy> selectPage(CouponBuy record);

	void deleteAll();

	int count(CouponBuy couponBuy);
}