package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.api.common.ResponseRestEntity;
import com.zbensoft.e.payment.db.domain.ConsumerFamilyCoupon;
import com.zbensoft.e.payment.db.domain.Coupon;
import com.zbensoft.e.payment.db.domain.CouponUserAndFamily;

public interface CouponService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int deleteByPrimaryKey(String couponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insert(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insertSelective(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	Coupon selectByPrimaryKey(String couponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKeySelective(Coupon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table reconciliation_bath
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKey(Coupon record);
	
	ResponseRestEntity<Coupon> updateStatus(String id);

	List<Coupon> selectPage(Coupon record);

	void deleteAll();

	int count(Coupon coupon);

	ResponseRestEntity<List<CouponUserAndFamily>> getConsumercoupon(String userId, String userName, int status, int limitType, String start, String length);

	List<Coupon> selectExpiredCoupon(Coupon couponSer);

	void insertCouponFamilyCoupon(Coupon toDBcoupon, List<ConsumerFamilyCoupon> toDBConsumerFamilyCouponList);

	List<Coupon> selectAvailableCoupon(Coupon newCouponSer);

	void updateWithFamilyCoupon(Coupon existCoupon);
}