package com.zbensoft.e.payment.api.service.api;

import java.util.List;


import com.zbensoft.e.payment.db.domain.DailyBill;

public interface DailyBillService {
    
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int deleteByPrimaryKey(DailyBill bean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int insert(DailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int insertSelective(DailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    DailyBill selectByPrimaryKey(DailyBill bean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(DailyBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int updateByPrimaryKey(DailyBill record);
    
    List<DailyBill> selectPage(DailyBill record);
    boolean isExist(DailyBill dailyBill);
    void deleteAll();

	int count(DailyBill dailyBill);

	void deleteByBillDate(String billDate);
}