package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ErrorHandling;

public interface ErrorHandlingService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int deleteByPrimaryKey(String errorHandlingId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insert(ErrorHandling record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int insertSelective(ErrorHandling record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	ErrorHandling selectByPrimaryKey(String errorHandlingId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKeySelective(ErrorHandling record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table error_handling
	 *
	 * @mbg.generated Thu May 25 16:26:59 CST 2017
	 */
	int updateByPrimaryKey(ErrorHandling record);

	List<ErrorHandling> selectPage(ErrorHandling record);

	void deleteAll();
    //2016-06-05
	int count(ErrorHandling errorHandling);
	void deleteByErrorHandling(ErrorHandling errorHandling);
}