package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultType;

public interface FraultTypeService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int deleteByPrimaryKey(String fraultTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int insert(FraultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int insertSelective(FraultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	FraultType selectByPrimaryKey(String fraultTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int updateByPrimaryKeySelective(FraultType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bank_info
	 *
	 * @mbg.generated Thu May 25 09:28:45 CST 2017
	 */
	int updateByPrimaryKey(FraultType record);

	List<FraultType> selectPage(FraultType record);

	boolean isFraultTypeExist(FraultType fraultType);

	void deleteAll();
	
	int count(FraultType fraultType);
}