package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultBankCard;

public interface FraultBankCardService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    int deleteByPrimaryKey(String fraultBankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    int insert(FraultBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    int insertSelective(FraultBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    FraultBankCard selectByPrimaryKey(String fraultBankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    int updateByPrimaryKeySelective(FraultBankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_bank_card
     *
     * @mbg.generated Tue Jun 27 18:46:33 CST 2017
     */
    int updateByPrimaryKey(FraultBankCard record);
    int deleteAll();
   	int count(FraultBankCard card);
   	List<FraultBankCard> selectPage(FraultBankCard record);
}
