package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultMerchant;

public interface FraultMerchantService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    int deleteByPrimaryKey(String fraultMerchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    int insert(FraultMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    int insertSelective(FraultMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    FraultMerchant selectByPrimaryKey(String fraultMerchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    int updateByPrimaryKeySelective(FraultMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_merchant
     *
     * @mbg.generated Wed Jun 28 16:34:29 CST 2017
     */
    int updateByPrimaryKey(FraultMerchant record);
    int deleteAll();
	int count(FraultMerchant number);
	List<FraultMerchant> selectPage(FraultMerchant number);
}
