package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultConsumer;

public interface FraultConsumerService {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    int deleteByPrimaryKey(String fraultConsumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    int insert(FraultConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    int insertSelective(FraultConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    FraultConsumer selectByPrimaryKey(String fraultConsumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    int updateByPrimaryKeySelective(FraultConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_consumer
     *
     * @mbg.generated Wed Jun 28 14:49:30 CST 2017
     */
    int updateByPrimaryKey(FraultConsumer record);
    int deleteAll();
   	int count(FraultConsumer card);
   	List<FraultConsumer> selectPage(FraultConsumer record);
}
