package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultModelProcess;

public interface FraultModelProcessService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int deleteByPrimaryKey(FraultModelProcess key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insert(FraultModelProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insertSelective(FraultModelProcess record);
    
	int updateByPrimaryKey(FraultModelProcess record);

	List<FraultModelProcess> selectPage(FraultModelProcess record);

	int deleteAll();

	int count(FraultModelProcess fraultModelProcess);
	
	FraultModelProcess selectByPrimaryKey(FraultModelProcess fraultModelProcess);

	int updateByPrimaryKeySelective(FraultModelProcess currentFraultModelProcess);

	List<FraultModelProcess> selectByModelId(String modelId);

}