package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultModelRule;

public interface FraultModelRuleService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int deleteByPrimaryKey(FraultModelRule key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insert(FraultModelRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insertSelective(FraultModelRule record);
    
	int updateByPrimaryKey(FraultModelRule record);

	List<FraultModelRule> selectPage(FraultModelRule record);

	int deleteAll();

	int count(FraultModelRule fraultModelRule);
	
	FraultModelRule selectByPrimaryKey(FraultModelRule fraultModelRule);

	int updateByPrimaryKeySelective(FraultModelRule currentPayAppGatway);

	List<FraultModelRule> selectByModelId(String fraultModelId);
	
	List<FraultModelRule> selectByRuleId(String selectByRuleId);

}