package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.FraultPhoneNumber;

public interface FraultPhoneNumberService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    int deleteByPrimaryKey(String fraultPhoneNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    int insert(FraultPhoneNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    int insertSelective(FraultPhoneNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    FraultPhoneNumber selectByPrimaryKey(String fraultPhoneNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    int updateByPrimaryKeySelective(FraultPhoneNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table frault_phone_number
     *
     * @mbg.generated Wed Jun 28 14:11:20 CST 2017
     */
    int updateByPrimaryKey(FraultPhoneNumber record);
    int deleteAll();
	int count(FraultPhoneNumber number);
	List<FraultPhoneNumber> selectPage(FraultPhoneNumber number);
}
