package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovMenu;
import com.zbensoft.e.payment.db.domain.GovMenuUserMenuResponse;
import com.zbensoft.e.payment.db.domain.SysMenuUserMenuParam;

public interface GovMenuService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int insert(GovMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int insertSelective(GovMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    GovMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int updateByPrimaryKeySelective(GovMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_rule
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int updateByPrimaryKey(GovMenu record);
    
    List<GovMenu> selectPage(GovMenu record);

	void deleteAll();
	boolean isGovExist(GovMenu menu);
	GovMenu selectByRovName(String name);
	int count(GovMenu govMenu);
	
	List<GovMenu> getRoleResources(String id);
	List<GovMenuUserMenuResponse> getUserMenus(SysMenuUserMenuParam sysMenuUserMenuParam, String weburl);
	GovMenu selectByMenuName(String name);


	List<GovMenu> findAll();

	void saveRoleRescours(String roleId, List<String> list);
}