package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovRoleUserKey;
import com.zbensoft.e.payment.db.domain.SysUsersAppKey;

public interface GovRoleUserService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(GovRoleUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(GovRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(GovRoleUserKey record);

	List<GovRoleUserKey> selectPage(GovRoleUserKey record);

	void deleteAll();

	GovRoleUserKey selectByPrimaryKey(GovRoleUserKey key);

	int updateByPrimaryKey(GovRoleUserKey record);

	int updateByPrimaryKeySelective(GovRoleUserKey record);

	int count(GovRoleUserKey govRoleUser);

	List<GovRoleUserKey> selectByUserId(String userId);

	

}