package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovRoleMenuKey;
import com.zbensoft.e.payment.db.domain.SysRole;

public interface GovRoleMenuService {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role_menu
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int deleteByPrimaryKey(GovRoleMenuKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role_menu
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insert(GovRoleMenuKey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role_menu
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insertSelective(GovRoleMenuKey record);
	int updateByPrimaryKey(GovRoleMenuKey record);
	GovRoleMenuKey selectByPrimaryKey(String roleId);
	int deleteAll();
	int updateByPrimaryKeySelective(GovRoleMenuKey record);
	List<GovRoleMenuKey> selectPage(GovRoleMenuKey record);
	boolean isRoleExist(GovRoleMenuKey key);
	int count(GovRoleMenuKey key);
}