package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovRole;
import com.zbensoft.e.payment.db.domain.SysRole;

public interface GovRoleService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insert(GovRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int insertSelective(GovRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	GovRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int updateByPrimaryKeySelective(GovRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gov_role
	 * @mbg.generated  Wed Jun 07 17:23:00 CST 2017
	 */
	int updateByPrimaryKey(GovRole record);



	int deleteAll();
	GovRole selectByRovName(String anme);
	List<GovRole> selectPage(GovRole record);
	boolean isRoleExist(GovRole role);
	int count(GovRole role);


}