package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovUserLoginHis;

public interface GovUserLoginHisService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int deleteByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insert(GovUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insertSelective(GovUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    GovUserLoginHis selectByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKeySelective(GovUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKey(GovUserLoginHis record);

	List<GovUserLoginHis> selectPage(GovUserLoginHis govUserLoginHis);

	int count(GovUserLoginHis govUserLoginHis);

	void deleteAll();
}