package com.zbensoft.e.payment.api.service.api;

import java.util.List;


import com.zbensoft.e.payment.db.domain.HelpDocument;

public interface HelpDocumentService {
    
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String documentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int insert(HelpDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int insertSelective(HelpDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    HelpDocument selectByPrimaryKey(String helpDocumentSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(HelpDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helpDocument
     *
     * @mbg.generated Thu May 25 14:29:16 GMT+08:00 2017
     */
    int updateByPrimaryKey(HelpDocument record);
    
    List<HelpDocument> selectPage(HelpDocument record);
    boolean isExist(HelpDocument helpDocument);
    int count(HelpDocument helpDocument);
}