package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import org.springframework.stereotype.Service;

import com.zbensoft.e.payment.db.domain.ConsumptionType;
import com.zbensoft.e.payment.db.domain.HelpDocType;
public interface HelpDocTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    int deleteByPrimaryKey(String helpDocTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    int insert(HelpDocType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    int insertSelective(HelpDocType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    HelpDocType selectByPrimaryKey(String helpDocTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    int updateByPrimaryKeySelective(HelpDocType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_doc_type
     *
     * @mbg.generated Tue Oct 17 10:42:50 CST 2017
     */
    int updateByPrimaryKey(HelpDocType record);
    
    HelpDocType findByName(String name);

	int deleteAll();
	
	boolean isHelpDocTypeExist(HelpDocType helpDocType);

	List<HelpDocType> selectPage(HelpDocType record);

	int count(HelpDocType helpDocType);
}