package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerGroup;
import com.zbensoft.e.payment.db.domain.ConsumerUser;
import com.zbensoft.e.payment.db.domain.MerchantGroup;
import com.zbensoft.e.payment.db.domain.MerchantUser;

public interface MerchantGroupService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String merchantGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int insert(MerchantGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int insertSelective(MerchantGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    MerchantGroup selectByPrimaryKey(String merchantGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(MerchantGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int updateByPrimaryKey(MerchantGroup record);

	int count(MerchantGroup merchantGroup);

	List<MerchantGroup> selectPage(MerchantGroup merchantGroup);

	boolean isNameExist(MerchantGroup merchantGroup);

	void deleteAll();

	int saveOrUpdate(List<String> list, String merchantGroupId,boolean deleteFlagAll);
	
	void statusEnable(String merchantGroupId);

	void statusDisable(String merchantGroupId);
}