package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantActiveStatistics;

public interface MerchantActiveStatisticsService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    int deleteByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    int insert(MerchantActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    int insertSelective(MerchantActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    MerchantActiveStatistics selectByPrimaryKey(String statisticsTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantActiveStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_active_statistics
     *
     * @mbg.generated Fri Dec 01 13:28:14 CST 2017
     */
    int updateByPrimaryKey(MerchantActiveStatistics record);
    List<MerchantActiveStatistics> selectPage(MerchantActiveStatistics record);
    boolean isMerchantActiveStatisticsExist(MerchantActiveStatistics record);
	int count(MerchantActiveStatistics record);
}
