package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantUserLoginHis;

public interface MerchantUserLoginHisService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int deleteByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insert(MerchantUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insertSelective(MerchantUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    MerchantUserLoginHis selectByPrimaryKey(String consumerUserLoginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantUserLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKey(MerchantUserLoginHis record);

	List<MerchantUserLoginHis> selectPage(MerchantUserLoginHis merchantUserLoginHis);

	int count(MerchantUserLoginHis merchantUserLoginHis);

	void deleteAll();

	int countDistin(MerchantUserLoginHis consumerUserLoginHisSer);
}