package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.api.config.spring.securityjwt.JwtAuthenticationResponse;
import com.zbensoft.e.payment.db.domain.MerchantEmployee;

public interface MerchantEmployeeService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	int deleteByPrimaryKey(String employeeUserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	int insert(MerchantEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	int insertSelective(MerchantEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	MerchantEmployee selectByPrimaryKey(String employeeUserId);
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	int updateByPrimaryKeySelective(MerchantEmployee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gov_user
	 *
	 * @mbg.generated Wed Jun 07 15:37:39 CST 2017
	 */
	int updateByPrimaryKey(MerchantEmployee record);

	List<MerchantEmployee> selectPage(MerchantEmployee record);

	boolean isMerchantEmployeeExist(MerchantEmployee merchantEmployee);

	void deleteAll();

	MerchantEmployee selectByIdNumber(String userName);

	List<MerchantEmployee> selectByUserId(String userId);



	int count(MerchantEmployee merchantEmployee);

	JwtAuthenticationResponse login(String userName, String password) throws Exception;
}