package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.GovMenu;
import com.zbensoft.e.payment.db.domain.MerchantRole;
import com.zbensoft.e.payment.db.domain.SysRole;

public interface MerchantRoleService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	int deleteByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	int insert(MerchantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	int insertSelective(MerchantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	MerchantRole selectByPrimaryKey(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	int updateByPrimaryKeySelective(MerchantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchant_role
	 * @mbg.generated  Thu Jun 08 14:41:42 CST 2017
	 */
	int updateByPrimaryKey(MerchantRole record);
	int deleteAll();
	int count(MerchantRole role);
	List<MerchantRole> selectPage(MerchantRole record);
	boolean isRoleExist(MerchantRole role);
	MerchantRole selectByMerName(String name);
}