package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantRoleUserKey;
import com.zbensoft.e.payment.db.domain.SysUsersAppKey;

public interface MerchantRoleUserService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(MerchantRoleUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(MerchantRoleUserKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(MerchantRoleUserKey record);

	List<MerchantRoleUserKey> selectPage(MerchantRoleUserKey record);

	void deleteAll();

	MerchantRoleUserKey selectByPrimaryKey(MerchantRoleUserKey key);

	int updateByPrimaryKey(MerchantRoleUserKey record);

	int updateByPrimaryKeySelective(MerchantRoleUserKey record);

	int count(MerchantRoleUserKey merchantRoleUser);

	List<MerchantRoleUserKey> selectByUserId(String userId);

	

}