package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantEmployeeRoleRelKey;

public interface MerchantEmployeeRoleRelService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(MerchantEmployeeRoleRelKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(MerchantEmployeeRoleRelKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_users_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(MerchantEmployeeRoleRelKey record);

	List<MerchantEmployeeRoleRelKey> selectPage(MerchantEmployeeRoleRelKey record);

	void deleteAll();

	MerchantEmployeeRoleRelKey selectByPrimaryKey(MerchantEmployeeRoleRelKey key);

	int updateByPrimaryKey(MerchantEmployeeRoleRelKey record);

	int updateByPrimaryKeySelective(MerchantEmployeeRoleRelKey record);

	int count(MerchantEmployeeRoleRelKey merchantEmployeeRoleRel);

	List<MerchantEmployeeRoleRelKey> selectByRoleId(String roleId);

	List<MerchantEmployeeRoleRelKey> selectByUserId(String userId);

	

}