package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantEmployeeLoginHis;

public interface MerchantEmployeeLoginHisService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int deleteByPrimaryKey(String loginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insert(MerchantEmployeeLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int insertSelective(MerchantEmployeeLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    MerchantEmployeeLoginHis selectByPrimaryKey(String loginHisId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantEmployeeLoginHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_user_login_his
     *
     * @mbg.generated Wed Jun 07 14:48:24 CST 2017
     */
    int updateByPrimaryKey(MerchantEmployeeLoginHis record);

	List<MerchantEmployeeLoginHis> selectPage(MerchantEmployeeLoginHis merchantEmployeeLoginHis);

	int count(MerchantEmployeeLoginHis merchantEmployeeLoginHis);

	void deleteAll();
}