package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ConsumerGroupUserKey;
import com.zbensoft.e.payment.db.domain.MerchantGroupUserKey;


public interface MerchantGroupUserService {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group_user
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int deleteByPrimaryKey(MerchantGroupUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group_user
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int insert(MerchantGroupUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_group_user
     *
     * @mbg.generated Tue Jun 20 13:25:16 GMT+08:00 2017
     */
    int insertSelective(MerchantGroupUserKey record);

	void deleteByGroupId(String merchantGroupId);

	int count(MerchantGroupUserKey merchantGroupUserKey);

	List<MerchantGroupUserKey> selectPage(MerchantGroupUserKey merchantGroupUserKey);

	void deleteMerchantGroupUser(MerchantGroupUserKey merchantGroupUserKey);
	List<MerchantGroupUserKey> selectByUserId(String userId);
}