package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MerchantTrade;

public interface MerchantTradeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int deleteByPrimaryKey(MerchantTrade key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insert(MerchantTrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insertSelective(MerchantTrade record);
    
	int updateByPrimaryKey(MerchantTrade record);

	List<MerchantTrade> selectPage(MerchantTrade record);

	int deleteAll();

	int count(MerchantTrade merchantTrade);
	
	MerchantTrade selectByPrimaryKey(MerchantTrade merchantTrade);

	int updateByPrimaryKeySelective(MerchantTrade currentMerchantTrade);
	
	List<MerchantTrade> selectByUserId(String userId);

	int countTwo(MerchantTrade merchantTrade);

	List<MerchantTrade> selectPageTwo(MerchantTrade record);

}