package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.MonthBillConsumptionDetail;

public interface MonthBillConsumptionDetailService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int deleteByPrimaryKey(MonthBillConsumptionDetail key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insert(MonthBillConsumptionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int insertSelective(MonthBillConsumptionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    MonthBillConsumptionDetail selectByPrimaryKey(MonthBillConsumptionDetail key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKeySelective(MonthBillConsumptionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill_consumption_detail
     *
     * @mbg.generated Mon Jun 19 15:47:39 CST 2017
     */
    int updateByPrimaryKey(MonthBillConsumptionDetail record);

	List<MonthBillConsumptionDetail> selectPage(MonthBillConsumptionDetail record);

	void deleteAll();

	int count(MonthBillConsumptionDetail monthBillConsumptionDetail);

	void deleteByBillDate(String billDate);

	List<MonthBillConsumptionDetail> queryMonthDetailDetails(String userId, String month);
}