package com.zbensoft.e.payment.api.service.api;

import java.util.List;


import com.zbensoft.e.payment.db.domain.MonthBill;

public interface MonthBillService {
    
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int deleteByPrimaryKey(MonthBill bean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int insert(MonthBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int insertSelective(MonthBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    MonthBill selectByPrimaryKey(MonthBill bean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(MonthBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table daily_bill
     *
     * @mbg.generated Thu May 25 14:17:27 GMT+08:00 2017
     */
    int updateByPrimaryKey(MonthBill record);
    
    List<MonthBill> selectPage(MonthBill record);
    boolean isExist(MonthBill monthBill);
    void deleteAll();

	int count(MonthBill monthBill);

	void deleteByBillDate(String billDate);

	List<MonthBill> queryLastFiveMonth(String userId, String []asList);

}