package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.PayAppGateway;

public interface PayAppGatewayService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int deleteByPrimaryKey(PayAppGateway key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insert(PayAppGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm_level_type
     *
     * @mbg.generated Fri Jun 09 15:47:28 CST 2017
     */
    int insertSelective(PayAppGateway record);
    
	int updateByPrimaryKey(PayAppGateway record);

	List<PayAppGateway> selectPage(PayAppGateway record);

	int deleteAll();

	int count(PayAppGateway payAppGatway);
	
	PayAppGateway selectByPrimaryKey(PayAppGateway payAppGatway);

	int updateByPrimaryKeySelective(PayAppGateway currentPayAppGatway);

	List<PayAppGateway> selectByPayAppId(String payAppId);

}