package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.PayGateway;

public interface PayGatewayService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int deleteByPrimaryKey(String payGatewayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int insert(PayGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int insertSelective(PayGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    PayGateway selectByPrimaryKey(String payGatewayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int updateByPrimaryKeySelective(PayGateway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_gateway
     *
     * @mbg.generated Thu May 25 10:46:10 CST 2017
     */
    int updateByPrimaryKey(PayGateway record);
    
    List<PayGateway> selectPage(PayGateway record);

	void deleteAll();

	int count(PayGateway payGateway);

	List<PayGateway> selectByBankBind(PayGateway payGateway);
}