package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.ReconciliationBank;
import com.zbensoft.e.payment.db.domain.ReconciliationBankKey;
import com.zbensoft.e.payment.db.domain.ReconciliationBatch;

public interface ReconciliationBankService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    int deleteByPrimaryKey(ReconciliationBankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    int insert(ReconciliationBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    int insertSelective(ReconciliationBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    ReconciliationBank selectByPrimaryKey(ReconciliationBankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    int updateByPrimaryKeySelective(ReconciliationBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reconciliation_bank
     *
     * @mbg.generated Sun Jul 30 14:59:07 VET 2017
     */
    int updateByPrimaryKey(ReconciliationBank record);
	List<ReconciliationBank> selectPage(ReconciliationBank record);



	int count(ReconciliationBank reconciliationBank);
}