package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.SysUserClap;

public interface SysUserClapService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(SysUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(SysUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	SysUserClap selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserClap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_clap
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(SysUserClap record);

	List<SysUserClap> selectPage(SysUserClap userClap);

	void deleteAll();

	int count(SysUserClap userClap);
}
