package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.SysUserBankCard;

public interface SysUserBankCardService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String bankBindId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(SysUserBankCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(SysUserBankCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	SysUserBankCard selectByPrimaryKey(String bankBindId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUserBankCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_user_bank_card
	 *
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(SysUserBankCard record);

	List<SysUserBankCard> selectPage(SysUserBankCard record);

	void deleteAll();

	int count(SysUserBankCard userBankCard);
}
