package com.zbensoft.e.payment.api.service.api;

import java.util.List;

import com.zbensoft.e.payment.db.domain.TransferType;

public interface TransferTypeService {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int deleteByPrimaryKey(String transferTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insert(TransferType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int insertSelective(TransferType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	TransferType selectByPrimaryKey(String transferTypeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKeySelective(TransferType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_app
	 * 
	 * @mbg.generated Thu May 25 15:26:15 CST 2017
	 */
	int updateByPrimaryKey(TransferType record);

	List<TransferType> selectPage(TransferType record);

	boolean isTransferTypeExist(TransferType transferType);

	void deleteAll();

	int count(TransferType transferType);
}